
site_name: CyberSecAI
site_url: https://github.com/CyberSecAI/CyberSecAI.github.io

# Page tree
nav:
  - Home: index.md
  - Introduction: 
    - Introduction: introduction/Introduction.md
    - Preface: introduction/Preface.md
  - NotebookLM:
    - NotebookLM: NotebookLM/NotebookLM.md
    - NotebookLM Vulnerability Standards: NotebookLM/NotebookLM_VulnerabilityStandards.md
    - NotebookLM CWE: NotebookLM/NotebookLM_Cwe.md
    - NotebookLM CAPEC: NotebookLM/NotebookLM_Capec.md
    - NotebookLM ATTACK: NotebookLM/NotebookLM_Attack.md
    - NotebookLM Config: NotebookLM/NotebookLM_Config.md
    - NotebookLM Secure Code: NotebookLM/NotebookLM_Secure_Code.md
  - Grounded Closed System: 
    - Grounding: Grounded/grounding.md
    - ChatGPT CWE GPT: Grounded/cwe_gpt.md
    - Vertex AI Agent: Grounded/vertex_ai.md
  - Prompting:
    - Prompt Engineering: prompt_engineering/prompt_engineering.md    
    - Fabric: prompt_engineering/Fabric.md    
  - Vulnrichment:
    - CISA Vulnrichment: Vulnrichment/Vulnrichment.md
  - TopicModeling:
    - BertTopic: TopicModeling/BertTopic.md
  - Annex:
    - Glossary: annex/Glossary.md
    - Talks & Research: research/research.md
  
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/head-plus

  features:
    - navigation.expand
    - navigation.footer
    ##- navigation.indexes
    ##- navigation.instant
    ###- navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    #- navigation.sections
    ##- navigation.tabs
    # - navigation.tabs.sticky
    ##- navigation.top
    ##- navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    #- toc.follow
    # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: cyan
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.snippets:
      auto_append: [includes/abbreviations.md]
      base_path: docs
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink # to hyperlink all urls
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true



extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # for sortable tables
  - javascripts/tablesort.js 


watch:
  - docs/includes
  - docs

extra:
  analytics:
    provider: google
    property: G-NMMB0KXVGQ
  social:
  - icon: fontawesome/solid/house
    link: https://github.com/CyberSecAI/CyberSecAI.github.io
    name: Guide
  - icon: fontawesome/solid/bug
    link: https://github.com/CyberSecAI/CyberSecAI.github.io/issues/
    name: Report an Issue or Suggest a Change
  - icon: fontawesome/brands/github
    link: https://github.com/CyberSecAI/CyberSecAI.github.io
    name: source on Github
  - icon: fontawesome/solid/download
    link: https://github.com/CyberSecAI/CyberSecAI.github.io/print_page/
    name: Save as HTML or print to PDF / paper

copyright: Copyright &copy; Contributors to the CyberSecAI Guide.

plugins:
  - search
  - print-site 

