
site_name: CyberSecAI
site_url: https://github.com/CyberSecAI/CyberSecAI.github.io

# Page tree
nav:
  - Home: index.md
  - NotebookML: NotebookML/NotebookML.md
  
  - Annex:
    - Glossary: annex/Glossary.md
  
    

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/fire-off
  features:
    - navigation.expand
    - navigation.footer
    ##- navigation.indexes
    ##- navigation.instant
    ###- navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    #- navigation.sections
    ##- navigation.tabs
    # - navigation.tabs.sticky
    ##- navigation.top
    ##- navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    #- toc.follow
    # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
        primary: light blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.snippets:
      auto_append: [includes/abbreviations.md]
      base_path: docs
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink # to hyperlink all urls
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true



extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # for sortable tables
  - javascripts/tablesort.js 


watch:
  - docs/includes
  - docs

extra:
  analytics:
    provider: google
    property: G-51FVYR35TJ
  social:
  - icon: fontawesome/solid/house
    link: https://github.com/RiskBasedPrioritization/RiskBasedPrioritization.github.io
    name: Risk Based Prioritization Guide
  - icon: fontawesome/solid/bug
    link: https://github.com/RiskBasedPrioritization/RiskBasedPrioritization.github.io/issues/
    name: Report an Issue or Suggest a Change
  - icon: fontawesome/brands/github
    link: https://github.com/RiskBasedPrioritization/RiskBasedPrioritization.github.io
    name: Risk Based Prioritization source on Github
  - icon: fontawesome/solid/download
    link: https://riskbasedprioritization.github.io/print_page/
    name: Save as HTML or print to PDF / paper

copyright: Copyright &copy; Contributors to the Risk Based Prioritization Guide.

plugins:
  - search
  - print-site 

